version: '3.8'

services:
  web:
    build: .
    container_name: smart_condo_web
    environment:
      - DEBUG=False
      - DB_HOST=smart_condo_db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432
      - REDIS_URL=redis://smart_condo_redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - backend
    restart: unless-stopped
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media

  nginx:
    image: nginx:alpine
    container_name: smart_condo_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - web
    networks:
      - backend
    restart: unless-stopped

  db:
    image: postgres:17
    container_name: smart_condo_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: smart_condo_redis
    networks:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge