version: '3.8'

services:
  db:
    image: postgres:17
    container_name: smart_condo_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: smart_condo_redis
    ports:
      - "6379:6379"
    networks:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  backend:
    external: true