// Smart Condominium - Tipografía
export const typography = {
  fontFamily: [
    'Inter',
    'Roboto',
    '-apple-system',
    'BlinkMacSystemFont',
    '"Segoe UI"',
    '"Helvetica Neue"',
    'Arial',
    'sans-serif',
    '"Apple Color Emoji"',
    '"Segoe UI Emoji"',
    '"Segoe UI Symbol"',
  ].join(','),
  h1: {
    fontSize: '2rem',
    fontWeight: 600,
    lineHeight: 1.2,
    fontFamily: 'Inter, sans-serif',
  },
  h2: {
    fontSize: '1.5rem',
    fontWeight: 600,
    lineHeight: 1.3,
    fontFamily: 'Inter, sans-serif',
  },
  h3: {
    fontSize: '1.25rem',
    fontWeight: 500,
    lineHeight: 1.4,
    fontFamily: 'Inter, sans-serif',
  },
  h4: {
    fontSize: '1.125rem',
    fontWeight: 500,
    lineHeight: 1.4,
    fontFamily: 'Inter, sans-serif',
  },
  h5: {
    fontSize: '1rem',
    fontWeight: 500,
    lineHeight: 1.5,
    fontFamily: 'Inter, sans-serif',
  },
  h6: {
    fontSize: '0.875rem',
    fontWeight: 500,
    lineHeight: 1.5,
    fontFamily: 'Inter, sans-serif',
  },
  body1: {
    fontSize: '1rem',
    fontWeight: 400,
    lineHeight: 1.5,
    fontFamily: 'Roboto, sans-serif',
  },
  body2: {
    fontSize: '0.875rem',
    fontWeight: 400,
    lineHeight: 1.43,
    fontFamily: 'Roboto, sans-serif',
  },
  button: {
    fontSize: '0.875rem',
    fontWeight: 500,
    lineHeight: 1.75,
    textTransform: 'none',
    fontFamily: 'Inter, sans-serif',
  },
  caption: {
    fontSize: '0.75rem',
    fontWeight: 400,
    lineHeight: 1.66,
    fontFamily: 'Roboto, sans-serif',
  },
  overline: {
    fontSize: '0.625rem',
    fontWeight: 400,
    lineHeight: 2.66,
    textTransform: 'uppercase',
    fontFamily: 'Roboto, sans-serif',
  },
};