# Generated by Django 5.2.6 on 2025-09-28 20:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('color', models.CharField(default='#007bff', help_text='Color hexadecimal (ej: #007bff)', max_length=7, verbose_name='Color')),
                ('icono', models.CharField(default='bell', help_text='Icono de Font Awesome o similar', max_length=50, verbose_name='Icono')),
                ('prioridad', models.IntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta'), (4, 'Crítica')], default=1, verbose_name='Prioridad')),
                ('esta_activa', models.BooleanField(default=True, verbose_name='Está Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría de Notificación',
                'verbose_name_plural': 'Categorías de Notificaciones',
                'db_table': 'categorias_notificaciones',
                'ordering': ['-prioridad', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AvisoGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('tipo_aviso', models.CharField(choices=[('informativo', 'Informativo'), ('importante', 'Importante'), ('urgente', 'Urgente'), ('mantenimiento', 'Mantenimiento'), ('reunion', 'Reunión'), ('evento', 'Evento'), ('cambio_reglamento', 'Cambio de Reglamento')], default='informativo', max_length=20, verbose_name='Tipo de Aviso')),
                ('es_destacado', models.BooleanField(default=False, verbose_name='Es Destacado')),
                ('mostrar_en_inicio', models.BooleanField(default=True, verbose_name='Mostrar en Inicio')),
                ('requiere_notificacion', models.BooleanField(default=True, verbose_name='Crear Notificación')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='avisos/portadas/', verbose_name='Imagen de Portada')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='avisos/archivos/', verbose_name='Archivo Adjunto')),
                ('dirigido_a', models.CharField(choices=[('todos', 'Todos los Usuarios'), ('residentes', 'Solo Residentes'), ('propietarios', 'Solo Propietarios'), ('inquilinos', 'Solo Inquilinos'), ('administradores', 'Solo Administradores'), ('seguridad', 'Personal de Seguridad'), ('mantenimiento', 'Personal de Mantenimiento'), ('edificio', 'Por Edificio'), ('unidades', 'Unidades Específicas'), ('usuarios', 'Usuarios Específicos')], default='todos', max_length=20, verbose_name='Dirigido a')),
                ('edificios_objetivo', models.JSONField(blank=True, default=list)),
                ('visualizaciones', models.PositiveIntegerField(default=0, verbose_name='Visualizaciones')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Me Gusta')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='Está Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Aviso General',
                'verbose_name_plural': 'Avisos Generales',
                'db_table': 'avisos_generales',
                'ordering': ['-es_destacado', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recibir_push', models.BooleanField(default=True, verbose_name='Recibir Notificaciones Push')),
                ('recibir_email', models.BooleanField(default=True, verbose_name='Recibir Emails')),
                ('recibir_sms', models.BooleanField(default=False, verbose_name='Recibir SMS')),
                ('notif_pagos', models.BooleanField(default=True, verbose_name='Notificaciones de Pagos')),
                ('notif_mantenimiento', models.BooleanField(default=True, verbose_name='Notificaciones de Mantenimiento')),
                ('notif_seguridad', models.BooleanField(default=True, verbose_name='Notificaciones de Seguridad')),
                ('notif_eventos', models.BooleanField(default=True, verbose_name='Notificaciones de Eventos')),
                ('notif_avisos', models.BooleanField(default=True, verbose_name='Avisos Generales')),
                ('notif_reservas', models.BooleanField(default=True, verbose_name='Notificaciones de Reservas')),
                ('horario_inicio', models.TimeField(default='07:00', verbose_name='Hora de Inicio')),
                ('horario_fin', models.TimeField(default='22:00', verbose_name='Hora de Fin')),
                ('no_molestar_fines_semana', models.BooleanField(default=False, verbose_name='No Molestar Fines de Semana')),
                ('token_fcm_android', models.TextField(blank=True, verbose_name='Token FCM Android')),
                ('token_fcm_ios', models.TextField(blank=True, verbose_name='Token FCM iOS')),
                ('token_fcm_web', models.TextField(blank=True, verbose_name='Token FCM Web')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Configuración de Notificaciones',
                'verbose_name_plural': 'Configuraciones de Notificaciones',
                'db_table': 'configuraciones_notificaciones',
            },
        ),
        migrations.CreateModel(
            name='DestinatarioNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('no_enviado', 'No Enviado'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('leido', 'Leído'), ('confirmado', 'Confirmado'), ('error', 'Error al Enviar')], default='no_enviado', max_length=20, verbose_name='Estado')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Lectura')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Confirmación')),
                ('dispositivo_lectura', models.CharField(blank=True, choices=[('web', 'Web'), ('movil', 'Móvil'), ('email', 'Email')], max_length=20, null=True, verbose_name='Dispositivo de Lectura')),
                ('mensaje_error', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('token_confirmacion', models.CharField(blank=True, max_length=100, verbose_name='Token de Confirmación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_destinatario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Destinatario de Notificación',
                'verbose_name_plural': 'Destinatarios de Notificaciones',
                'db_table': 'destinatarios_notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='InteraccionAviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_interaccion', models.CharField(choices=[('visualizacion', 'Visualización'), ('like', 'Me Gusta'), ('dislike', 'No Me Gusta'), ('compartir', 'Compartir')], max_length=20, verbose_name='Tipo de Interacción')),
                ('fecha_interaccion', models.DateTimeField(auto_now_add=True)),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='comunicacion.avisogeneral', verbose_name='Aviso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones_avisos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Interacción con Aviso',
                'verbose_name_plural': 'Interacciones con Avisos',
                'db_table': 'interacciones_avisos',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('tipo_destinatario', models.CharField(choices=[('todos', 'Todos los Usuarios'), ('residentes', 'Solo Residentes'), ('propietarios', 'Solo Propietarios'), ('inquilinos', 'Solo Inquilinos'), ('administradores', 'Solo Administradores'), ('seguridad', 'Personal de Seguridad'), ('mantenimiento', 'Personal de Mantenimiento'), ('edificio', 'Por Edificio'), ('unidades', 'Unidades Específicas'), ('usuarios', 'Usuarios Específicos')], default='todos', max_length=20, verbose_name='Tipo de Destinatario')),
                ('edificios_objetivo', models.JSONField(blank=True, default=list, help_text="Lista de edificios objetivo ['A', 'B', 'C']", verbose_name='Edificios Objetivo')),
                ('unidades_objetivo', models.JSONField(blank=True, default=list, help_text='Lista de IDs de unidades objetivo [1, 2, 3]', verbose_name='Unidades Objetivo')),
                ('es_push', models.BooleanField(default=True, verbose_name='Notificación Push')),
                ('es_email', models.BooleanField(default=False, verbose_name='Enviar Email')),
                ('es_sms', models.BooleanField(default=False, verbose_name='Enviar SMS')),
                ('es_urgente', models.BooleanField(default=False, verbose_name='Es Urgente')),
                ('enviar_inmediatamente', models.BooleanField(default=True, verbose_name='Enviar Inmediatamente')),
                ('fecha_programada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Programada')),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Expiración')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='notificaciones/imagenes/', verbose_name='Imagen')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='notificaciones/archivos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'png'])], verbose_name='Archivo Adjunto')),
                ('requiere_confirmacion', models.BooleanField(default=False, verbose_name='Requiere Confirmación')),
                ('metadatos', models.JSONField(blank=True, default=dict, help_text='Datos adicionales en formato JSON', verbose_name='Metadatos')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('programada', 'Programada'), ('enviada', 'Enviada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20, verbose_name='Estado')),
                ('total_destinatarios', models.PositiveIntegerField(default=0, verbose_name='Total Destinatarios')),
                ('total_enviados', models.PositiveIntegerField(default=0, verbose_name='Total Enviados')),
                ('total_leidos', models.PositiveIntegerField(default=0, verbose_name='Total Leídos')),
                ('total_confirmados', models.PositiveIntegerField(default=0, verbose_name='Total Confirmados')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='comunicacion.categorianotificacion', verbose_name='Categoría')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('usuarios_especificos', models.ManyToManyField(blank=True, related_name='notificaciones_recibidas', through='comunicacion.DestinatarioNotificacion', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios Específicos')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='destinatarionotificacion',
            name='notificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='comunicacion.notificacion', verbose_name='Notificación'),
        ),
        migrations.CreateModel(
            name='PlantillaNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('titulo_plantilla', models.CharField(max_length=200, verbose_name='Título (Plantilla)')),
                ('mensaje_plantilla', models.TextField(verbose_name='Mensaje (Plantilla)')),
                ('variables_disponibles', models.JSONField(default=dict, help_text='Variables que se pueden usar: {usuario}, {unidad}, {fecha}, etc.', verbose_name='Variables Disponibles')),
                ('es_push_default', models.BooleanField(default=True, verbose_name='Push por Defecto')),
                ('es_email_default', models.BooleanField(default=False, verbose_name='Email por Defecto')),
                ('es_sistema', models.BooleanField(default=False, verbose_name='Es del Sistema')),
                ('esta_activa', models.BooleanField(default=True, verbose_name='Está Activa')),
                ('uso_contador', models.PositiveIntegerField(default=0, verbose_name='Veces Utilizada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria_default', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comunicacion.categorianotificacion', verbose_name='Categoría por Defecto')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Plantilla de Notificación',
                'verbose_name_plural': 'Plantillas de Notificaciones',
                'db_table': 'plantillas_notificaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='avisogeneral',
            index=models.Index(fields=['tipo_aviso'], name='avisos_gene_tipo_av_2a5e24_idx'),
        ),
        migrations.AddIndex(
            model_name='avisogeneral',
            index=models.Index(fields=['esta_activo'], name='avisos_gene_esta_ac_0fcded_idx'),
        ),
        migrations.AddIndex(
            model_name='avisogeneral',
            index=models.Index(fields=['fecha_inicio'], name='avisos_gene_fecha_i_30c029_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interaccionaviso',
            unique_together={('aviso', 'usuario', 'tipo_interaccion')},
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['estado'], name='notificacio_estado_579d44_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['tipo_destinatario'], name='notificacio_tipo_de_50b5c1_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['fecha_programada'], name='notificacio_fecha_p_627434_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['es_urgente'], name='notificacio_es_urge_888c68_idx'),
        ),
        migrations.AddIndex(
            model_name='destinatarionotificacion',
            index=models.Index(fields=['estado'], name='destinatari_estado_cac99d_idx'),
        ),
        migrations.AddIndex(
            model_name='destinatarionotificacion',
            index=models.Index(fields=['fecha_lectura'], name='destinatari_fecha_l_b283d2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='destinatarionotificacion',
            unique_together={('notificacion', 'usuario')},
        ),
    ]
