# Generated by Django 5.2.6 on 2025-09-27 21:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Tipo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('es_recurrente', models.BooleanField(default=True, verbose_name='Es Recurrente')),
                ('monto_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto Base')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='Está Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Pago',
                'verbose_name_plural': 'Tipos de Pagos',
                'db_table': 'tipos_pagos',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Total')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto Pagado')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('vencido', 'Vencido'), ('parcial', 'Pago Parcial'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('periodo', models.CharField(help_text='Formato: YYYY-MM (ej: 2025-01)', max_length=7, verbose_name='Período')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('referencia_pago', models.CharField(blank=True, max_length=100, verbose_name='Referencia de Pago')),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes/', verbose_name='Comprobante')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('usuario_pagador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Paga')),
                ('tipo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='finanzas.tipopago', verbose_name='Tipo de Pago')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
                'ordering': ['-fecha_vencimiento', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_transaccion', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto de la Transacción')),
                ('estado_anterior', models.CharField(max_length=20, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(max_length=20, verbose_name='Estado Nuevo')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('deposito', 'Depósito Bancario'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('qr', 'Código QR'), ('otro', 'Otro')], default='transferencia', max_length=50, verbose_name='Método de Pago')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Referencia')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True)),
                ('procesado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Procesado por')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='finanzas.pago', verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Historial de Pago',
                'verbose_name_plural': 'Historial de Pagos',
                'db_table': 'historial_pagos',
                'ordering': ['-fecha_transaccion'],
            },
        ),
        migrations.CreateModel(
            name='UnidadHabitacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_unidad', models.CharField(max_length=10, unique=True, verbose_name='Número de Unidad')),
                ('edificio', models.CharField(max_length=10, verbose_name='Edificio')),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Área (m²)')),
                ('dormitorios', models.PositiveIntegerField(verbose_name='Número de Dormitorios')),
                ('esta_activa', models.BooleanField(default=True, verbose_name='Está Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('inquilino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_alquiladas', to=settings.AUTH_USER_MODEL, verbose_name='Inquilino')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_propias', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Unidad Habitacional',
                'verbose_name_plural': 'Unidades Habitacionales',
                'db_table': 'unidades_habitacionales',
                'ordering': ['edificio', 'numero_unidad'],
            },
        ),
        migrations.AddField(
            model_name='pago',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='finanzas.unidadhabitacional', verbose_name='Unidad'),
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_multa', models.CharField(choices=[('retraso_pago', 'Retraso en Pago'), ('ruido', 'Ruido Excesivo'), ('mascotas', 'Incumplimiento Normas Mascotas'), ('areas_comunes', 'Mal Uso Áreas Comunes'), ('estacionamiento', 'Mal Uso Estacionamiento'), ('basura', 'Manejo Inadecuado de Basura'), ('otro', 'Otro')], max_length=50, verbose_name='Tipo de Multa')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_infraccion', models.DateField(verbose_name='Fecha de Infracción')),
                ('esta_pagada', models.BooleanField(default=False, verbose_name='Está Pagada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('aplicada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Aplicada por')),
                ('pago_asociado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.pago', verbose_name='Pago Asociado')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='finanzas.unidadhabitacional', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Multa',
                'verbose_name_plural': 'Multas',
                'db_table': 'multas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['estado'], name='pagos_estado_79b102_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['fecha_vencimiento'], name='pagos_fecha_v_911ae1_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['periodo'], name='pagos_periodo_f86013_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['unidad', 'periodo'], name='pagos_unidad__fcc81b_idx'),
        ),
    ]
